repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: name-tests-test
        args: [--pytest-test-first]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: "v1.12.0"
    hooks:
      - id: mypy
        args: []
        exclude: tests/
        additional_dependencies:
          - types-PyYAML
          - types-python-dateutil
          - sqlalchemy
          - pandas-stubs
          - python-dateutil
